config/routes.rb
Prelaunchr::Application.routes.draw do

  ActiveAdmin.routes(self)

  devise_for :admin_users, ActiveAdmin::Devise.config

  root :to => "users#new"

  post 'users/create' => 'users#create'
  post 'save_image' , :to => redirect('/save_image.php')
  get 'refer-a-friend' => 'users#refer'
  get 'privacy-policy' => 'users#policy'
  get 'iondesign' => 'users#customise'
  get 'order_confirmed' => 'users#order_confirmed'
  get 'demo' => 'users#demo'
  authenticate :admin_user do
    get 'dashboard' => 'users#dashboard'
    get 'dashboard/:order_id' => 'orders#show', as: 'dashboard_order'
  end
  resources :confirms
  
  
  resources :users do
    member do
      get :confirm_email
    end
  end
  
  resources :orders

  unless Rails.application.config.consider_all_requests_local
    get '*not_found', to: 'users#redirect', :format => false
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessor :image_json
  #before_validation :set_image
  
  validates_presence_of :email
  validates_presence_of :order_number
  has_attached_file :design, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :design, content_type: /\Aimage\/.*\z/
  has_one :confirm
  has_many :pictures
  
  def set_image(image_json)
      StringIO.open(Base64.decode64(image_json)) do |data|
        data.class.class_eval { attr_accessor :original_filename, :content_type }
        data.original_filename = "file.jpg"
        data.content_type = "image/jpeg"
        self.design = data
      end
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
 
  
  def create
    @order = Order.new(order_params)
    data_url = params[:order][:image_json]
    #@order.set_image(data_url)
    image = Paperclip.io_adapters.for(params[:order][:image_json])
    image.original_filename = "base.png"
    @order.design = image
    #images = params[:order][:images_json]
    #images = images.first['source']
    #puts images
    #images.each do |k, v|
      #image = Paperclip.io_adapters.for(v["source"])
      #image.original_filename = v["title"] + ".png"
      #@picture = Picture.new
      #@picture.image = image
      #@picture.order_id = @order.id
      #@picture.save
      #end
    #puts "HAHAHAHAHA"
    #params[:order][:image_json] = params[:order][:image_json]['data:image/png;base64,'.length..-1]
    #Base64.decode64(data_url['data:image/png;base64,'.length..-1])
    #png = Base64.decode64(data_url['data:image/png;base64,'.length..-1])
    #File.open('text.png','wb') {|f| f.write(png)}
    if @order.save
      images = params[:order][:images_json]
      ImageWorker.perform_async(images, @order.id)
      @confirm = Confirm.new
      render :partial => 'checkout'
    else
      puts "FAILED"
      puts @order.errors.full_messages
      render :json => { :error => @order.errors.full_messages }, :status => 422
    end
  end
  
  def show
    @order = Order.find(params[:order_id])
  end
  
  
  private
  
  def order_params
    params.require(:order).permit(:name, :email, :order_number, :design, :amount)
  end
  
end

app/views/orders/_checkout.html.erb
          <%= form_for @confirm do |f| %>
          <%= f.hidden_field :order_id, value: @order.id %>
          <%= f.hidden_field :amount, value: 39 %>
          <div class="form-group">
            <label for="exampleFormControlInput1">Full Name</label>
            <%= f.text_field :name, class: "form-control" %>
          </div>
          <script
            src="https://checkout.stripe.com/checkout.js" class="stripe-button"
            data-key="<%= ENV["STRIPE_PUB_KEY"] %>"
            data-amount="3900"
            data-name="ionboard"
            data-description="Premium electric skateboard for all"
            data-image="https://www.ionboardtech.com/images/skateboard/logo-ionboard.png"
            data-locale="auto">
          </script>
            
          <% end %>
            

app/views/orders/show.html.erb
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

<style>
  /*
   * Base structure
   */

  /* Move down content because we have a fixed navbar that is 50px tall */
  body {
    padding-top: 50px;
  }


  /*
   * Global add-ons
   */

  .sub-header {
    padding-bottom: 10px;
    border-bottom: 1px solid #eee;
  }

  /*
   * Top navigation
   * Hide default border to remove 1px line.
   */
  .navbar-fixed-top {
    border: 0;
  }

  /*
   * Sidebar
   */

  /* Hide for mobile, show later */
  .sidebar {
    display: none;
  }
  @media (min-width: 768px) {
    .sidebar {
      position: fixed;
      top: 51px;
      bottom: 0;
      left: 0;
      z-index: 1000;
      display: block;
      padding: 20px;
      overflow-x: hidden;
      overflow-y: auto; /* Scrollable contents if viewport is shorter than content. */
      background-color: #f5f5f5;
      border-right: 1px solid #eee;
    }
  }

  /* Sidebar navigation */
  .nav-sidebar {
    margin-right: -21px; /* 20px padding + 1px border */
    margin-bottom: 20px;
    margin-left: -20px;
  }
  .nav-sidebar > li > a {
    padding-right: 20px;
    padding-left: 20px;
  }
  .nav-sidebar > .active > a,
  .nav-sidebar > .active > a:hover,
  .nav-sidebar > .active > a:focus {
    color: #fff;
    background-color: #428bca;
  }


  /*
   * Main content
   */

  .main {
    padding: 20px;
  }
  @media (min-width: 768px) {
    .main {
      padding-right: 40px;
      padding-left: 40px;
    }
  }
  .main .page-header {
    margin-top: 0;
  }


  /*
   * Placeholder dashboard ideas
   */

  .placeholders {
    margin-bottom: 30px;
    text-align: center;
  }
  .placeholders h4 {
    margin-bottom: 0;
  }
  .placeholder {
    margin-bottom: 20px;
  }
  .placeholder img {
    display: inline-block;
    border-radius: 50%;
  }

  
  </style>
 <body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">ionboard</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">
            <li><a href="#">Dashboard</a></li>
            <li><a href="#">Settings</a></li>
            <li><a href="#">Profile</a></li>
            <li><a href="#">Help</a></li>
          </ul>
          <form class="navbar-form navbar-right">
            <input type="text" class="form-control" placeholder="Search...">
          </form>
        </div>
      </div>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
          </ul>
          
        </div>
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          <h1 class="page-header">Dashboard</h1>

        

          <h2 class="sub-header">Images</h2>
          <% @order.pictures.in_groups_of(3, false).each do |group| %>
           <div class="row">
             <% group.each do |picture| %>
             
            <div class="col-md-4">
              <div class="thumbnail">
                <%= link_to image_tag(picture.image.url(:thumb)), picture.image.url(:original), :popup=>['original_image'] %>

              </div>
            </div>
            <% end %>
            
          </div>
          <% end %>
          <%= link_to dashboard_path do %>
          <div class="btn btn-primary">Back to dashboard</div>
          <% end %>
        </div>
        
      </div>
      
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="../../dist/js/bootstrap.min.js"></script>
    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->
    <script src="../../assets/js/vendor/holder.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>